// <auto-generated />
using System;
using Parking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Parking.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20241210193943_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Parking.Models.ParkingSpot", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("Release")
                    .HasColumnType("datetime(6)");

                b.Property<int>("SpotNumber")
                    .HasColumnType("int");

                b.Property<DateTime>("Occupation")
                    .HasColumnType("datetime(6)");

                b.Property<bool>("Status")
                    .HasColumnType("tinyint(1)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("ParkingSpots");
            });
#pragma warning restore 612, 618
        }
    }
}
